exercises/Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
]

exercises/Blog/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index_view,name='index'),
    path('new/', views.create_view,name='new'),
    path('edit/<int:blog_id>/', views.edit_view,name='edit'),
]

exercises/Blog/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/',views.register, name='register')
]

exercises/Blog/blogs/models.py
from django.db import models

# Create your models here.

class Blogpost(models.Model):
    '''model for blogpost'''
    title = models.CharField(max_length=200,unique=True)
    text = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.title

exercises/Blog/users/models.py
from django.db import models

# Create your models here.

exercises/Blog/blogs/forms.py
from .models import Blogpost

from  django import forms

class CreateForm(forms.ModelForm):
    class Meta:
        model= Blogpost
        fields=['title','text','date']
        labels={'text': ''}

exercises/Blog/blogs/views.py
from django.shortcuts import render, redirect
from .models import Blogpost
from .forms import CreateForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
# Create your views here.

def index_view(request):
    posts = Blogpost.objects.order_by('date')
    context={'posts' : posts}

    return render(request, 'blogs/index.html', context)

@login_required
def create_view(request):
    if request.method != 'POST':
        form=CreateForm()
    else:
        form=CreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
    context= {'form':form}

    return render(request, 'blogs/new_post.html',context) 

@login_required
def edit_view(request, blog_id):
    blogpost = Blogpost.objects.get(id=blog_id)


    if request.method != 'POST':
        form=CreateForm(instance=blogpost)
    else:
        form=CreateForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
    context= {'blogpost':blogpost,'form':form}        


    return render(request, 'blogs/edit_post.html',context)                    

exercises/Blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def register(request):

    if request.method !='POST':
        form=UserCreationForm
    else:
        form=UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user=form.save()
            login(request,new_user)
            return redirect('blogs:index')

    context={'form':form}

    return render(request, 'registration/register.html', context)        

exercises/Blog/blogs/templates/blogs/base.html
<p>
    <a href="{% url  'blogs:index' %}">Blog</a> -

    {% if user.is_authenticated %}
    Hello,{{ user.username }}.
    <a href="{% url 'users:logout' %}">Log out</a>

    {%else %}

    <a href="{% url 'users:login' %}">Log in</a> -
    <a href="{% url 'users:register' %}">Register</a>

    {% endif %}
</p>

{% block content %}{% endblock content %}

exercises/Blog/blogs/templates/blogs/edit_post.html
<h2>Edit blog post</h2>



<form action="{% url 'blogs:edit' blogpost.id %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">edit Post</button>

</form>

exercises/Blog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}

<h1>Home</h1>

<ul>
    {% for post in posts %}
    <li>{{post}}</li>


    {% endfor %}


</ul>

{% endblock content %}

exercises/Blog/blogs/templates/blogs/new_post.html
<h2>Create new blog post</h2>



<form action="{% url 'blogs:new' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">Add Post</button>

</form>

exercises/Blog/users/templates/users/login.html
{% extends "learning_logs/base.html" %}

{% block content %}
{% if form.errors %}
<p>Yours username and password didn't match. Please try again</p>
{% endif %}
<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Log in</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">

</form>



{% endblock content %}