exercises/pizzeria/pizzas/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='pizzas'
urlpatterns = [
    path('',views.index_view, name='index' ),
    path('pizzas/',views.list_view, name='pizza_list' ),
    path('pizzas/<int:pizza_id>/',views.detail_view, name='pizza_detail' )
]

exercises/pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

exercises/pizzeria/pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return(self.name)

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    name=models.CharField(max_length=200)

    def __str__(self):
        return(self.name)

exercises/pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Pizza, Topping

# Create your views here.

def index_view(request):
    return render(request, 'pizzas/index.html') 

def list_view(request):
    pizzas=Pizza.objects.all()
    context = {'pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html', context)   

def detail_view(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name')
    
    context = {'pizza':pizza, 'toppings':toppings}

    return render(request, 'pizzas/detail.html', context)

exercises/pizzeria/pizzas/templates/pizzas/base.html
<!DOCTYPE html>

<html>

<head>
    <title>Pizzeria</title>
</head>
<h3><a href="{% url 'pizzas:index' %}">Pizzeria</a> - <a href="{% url 'pizzas:pizza_list' %}">Our menu</a></h3>

{% block content %}{% endblock content %}

</html>

exercises/pizzeria/pizzas/templates/pizzas/detail.html
{% extends "pizzas/base.html" %}

{% block content %}
<h2>{{pizza}}</h2>
<ul>
    {% for topping in toppings %}
    <li>{{ topping }}</li>

    {% endfor %}
</ul>
{% endblock content %}

exercises/pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>This is a page for customizing your pizza!</p>

{% endblock content %}

exercises/pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
<ul>
    {% for pizza in pizzas %}
    <li><a href="{% url 'pizzas:pizza_detail' pizza.id %}">{{ pizza }}</a></li>

    {% empty %}
    sorry, page is still under construction


    {% endfor %}
</ul>
{% endblock content %}